[package]
name = "pagebridge-py"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Python bindings for pagebridge"

[lib]
name = "_pagebridge"
crate-type = ["cdylib", "rlib"]

[dependencies]
pagebridge-core.workspace = true

[lints]
workspace = true
