"""Type stubs for the PyO3 extension module."""

from typing import Any

__version__: str

class Pagebridge:
    @staticmethod
    async def open_sqlite(path: str, ollama_url: str = ..., model: str = ...) -> "Pagebridge": ...
    @staticmethod
    async def open_embedded(path: str, ollama_url: str = ..., model: str = ...) -> "Pagebridge": ...
    async def ingest_document(self, text: bytes, title: str, kind: str = ...) -> str: ...
    async def wait_for_summaries(self, doc_id: str) -> None: ...
    async def ask(self, question: str) -> str: ...
    async def list_documents(self) -> str: ...
    async def remove_document(self, doc_id: str) -> None: ...
